### ISSUE TITLE
`stmocli track` could generate its own filenames

### ISSUE THREAD

**Issue by tdsmith** [mozilla/stmocli#17]
Feature idea for improved ergonomics: `stmocli track` could automatically generate filenames from the query titles instead of requiring a user-specified filename, in the case that the user doesn't really care.

ex. `stmocli track 1012` could read the query title and automatically track as `1012_devtools_dau_mau_er_by_channel.sql`.

**Comment by harterrt** [comment]
Sounds good to me.
