### ISSUE TITLE
Duplicated query code

### ISSUE THREAD

**Issue by tdsmith** [mozilla/stmocli#19]
I'm looking at a family of devtools-related queries that share a lot of copy-pasted logic between them, and the amount of duplicated code is giving me the heebie-jeebies.

Is this a problem stmocli should help solve?

One way it _could_ help is if stmocli allowed bundling query snippets inside the repository and including them directly into queries. This would add a "build" (or "render") step to the tool's responsibilities before it deploys the final SQL to stmo.

This means that a single change to a template could break _n_ queries at once. This could be difficult to detect without actually running those _n_ queries, which could be expensive, and asking a human expert to make a judgement about whether the query broke or not.

It's also possible that stmocli is entirely the wrong layer to be addressing this problem in, and we should be encouraging e.g. more derived tables instead of running the same query all the time.

**Comment by harterrt** [comment]
Thanks, @tdsmith. I've toyed with this idea as well. I like the idea of reducing query repetition by providing some templating functionality. However, I don't think that functionality should live in St. Mocli.

Instead, what if you used a custom script to generate the final SQL queries and St. Mocli to deploy. If it becomes a common use case, I'm open to adding hooks to St. Mocli for pre-deploy rendering.
